// lib/quizData.ts
import { Question, ItemProfile, Result, CafeKey } from "./types";

/** 10 questions, 2–3 options each */
export const QUESTIONS: Question[] = [
  {
    id: "q1",
    prompt: "Morning vibe?",
    options: [
      { id: "q1o1", label: "Ease into it", delta: { energy: 0, trendy: 1, social: 1 } },
      { id: "q1o2", label: "Hit the ground running", delta: { energy: 2, bitter: 1 } },
      { id: "q1o3", label: "Sprint from first step", delta: { energy: 3, bitter: 2 } },
    ],
  },
  {
    id: "q2",
    prompt: "Social preference?",
    options: [
      { id: "q2o1", label: "Big group energy", delta: { social: 3, chaos: 1 } },
      { id: "q2o2", label: "Small circle", delta: { social: 1, trendy: 1 } },
      { id: "q2o3", label: "Solo mode", delta: { social: -1, bitter: 1 } },
    ],
  },
  {
    id: "q3",
    prompt: "Coffee order style?",
    options: [
      { id: "q3o1", label: "Black, simple", delta: { bitter: 3, trendy: -1 } },
      { id: "q3o2", label: "With milk/sweetener", delta: { bitter: -1, social: 1 } },
    ],
  },
  {
    id: "q4",
    prompt: "Trying new trends?",
    options: [
      { id: "q4o1", label: "Always first", delta: { trendy: 3, chaos: 1 } },
      { id: "q4o2", label: "Wait and see", delta: { trendy: 0, bitter: 1 } },
      { id: "q4o3", label: "Stick to classics", delta: { trendy: -2, bitter: 2 } },
    ],
  },
  {
    id: "q5",
    prompt: "Work style?",
    options: [
      { id: "q5o1", label: "Planned and steady", delta: { energy: 1, chaos: -1 } },
      { id: "q5o2", label: "Bursts of focus", delta: { energy: 2, chaos: 1 } },
      { id: "q5o3", label: "Wing it", delta: { chaos: 3, energy: -1 } },
    ],
  },
  {
    id: "q6",
    prompt: "Late night?",
    options: [
      { id: "q6o1", label: "Still going strong", delta: { energy: 2, chaos: 1 } },
      { id: "q6o2", label: "Winding down", delta: { energy: -1, social: 1 } },
    ],
  },
  {
    id: "q7",
    prompt: "Weekend plans?",
    options: [
      { id: "q7o1", label: "Trying something new", delta: { trendy: 2, chaos: 1 } },
      { id: "q7o2", label: "Favorite routine", delta: { trendy: -1, energy: 1 } },
      { id: "q7o3", label: "Whatever happens", delta: { chaos: 2, social: 1 } },
    ],
  },
  {
    id: "q8",
    prompt: "Handling setbacks?",
    options: [
      { id: "q8o1", label: "Push through", delta: { energy: 2, bitter: 1 } },
      { id: "q8o2", label: "Adapt and pivot", delta: { chaos: 1, social: 1 } },
    ],
  },
  {
    id: "q9",
    prompt: "Aesthetics matter?",
    options: [
      { id: "q9o1", label: "Very much", delta: { trendy: 2, social: 1 } },
      { id: "q9o2", label: "Function over form", delta: { bitter: 2, trendy: -1 } },
      { id: "q9o3", label: "Depends on mood", delta: { chaos: 1 } },
    ],
  },
  {
    id: "q10",
    prompt: "Risk tolerance?",
    options: [
      { id: "q10o1", label: "High—let's try it", delta: { chaos: 2, energy: 1 } },
      { id: "q10o2", label: "Calculated risks", delta: { energy: 1, social: 1 } },
      { id: "q10o3", label: "Play it safe", delta: { chaos: -1, bitter: 1 } },
    ],
  },
];

/** 12 item profiles (logic targets) */
export const ITEM_PROFILES: ItemProfile[] = [
  { key: "matcha_latte",        target: { energy: 4, trendy: 6, bitter: 3, social: 5, chaos: 2 } },
  { key: "iced_milk_coffee",    target: { energy: 6, trendy: 5, bitter: 5, social: 6, chaos: 3 } },
  { key: "hot_black",           target: { energy: 7, trendy: 2, bitter: 9, social: 3, chaos: 2 } },
  { key: "americano",           target: { energy: 6, trendy: 3, bitter: 8, social: 4, chaos: 2 } },
  { key: "cappuccino",          target: { energy: 5, trendy: 4, bitter: 4, social: 7, chaos: 2 } },
  { key: "espresso",            target: { energy: 9, trendy: 3, bitter: 9, social: 4, chaos: 3 } },
  { key: "iced_water",          target: { energy: 2, trendy: 5, bitter: 5, social: 5, chaos: 1 } },
  { key: "breakfast_sandwich",  target: { energy: 4, trendy: 4, bitter: 3, social: 6, chaos: 2 } },
  { key: "chai",                target: { energy: 4, trendy: 6, bitter: 2, social: 7, chaos: 3 } },
  { key: "avocado_toast",       target: { energy: 5, trendy: 9, bitter: 3, social: 7, chaos: 4 } },
  { key: "croissant",           target: { energy: 3, trendy: 6, bitter: 4, social: 6, chaos: 2 } },
  { key: "secret_chair",        target: { energy: 5, trendy: 5, bitter: 5, social: 5, chaos: 9 } },
];

/** Display copy for 12 items (no emojis) */
export const RESULTS: Record<CafeKey, Result> = {
  matcha_latte: {
    key: "matcha_latte",
    title: "You're Matcha Latte",
    blurb: "Calm energy and modern taste. You like steady mornings and thoughtful choices.",
    explanation: "You're a Matcha Latte because you value balance over extremes. Your answers show you prefer thoughtful approaches and steady progress, just like matcha's gentle, sustained energy.",
    traits: ["balanced", "mindful routine", "gentle starter"],
    colorClass: "from-emerald-300 to-emerald-600",
    bestPairings: ["avocado_toast", "croissant"],
    worstPairings: ["espresso", "hot_black"],
    cafePersona: "Deep Thinker",
    vibeLevel: 75,
    vibeLabel: "Zen Energy",
    luckyCharm: "Notebook",
    tablemates: ["chai", "avocado_toast"],
    neighboringTables: ["espresso", "hot_black"],
  },
  iced_milk_coffee: {
    key: "iced_milk_coffee",
    title: "You're Iced Coffee with Milk",
    blurb: "Approachable energy and flexible style. You flow between social and solo.",
    explanation: "You're an Iced Coffee with Milk because you're adaptable and easygoing. Your choices reveal a blend of energy and chill—ready to engage but never overwhelming.",
    traits: ["adaptable", "friendly", "versatile"],
    colorClass: "from-sky-300 to-sky-600",
    bestPairings: ["breakfast_sandwich", "croissant"],
    worstPairings: ["iced_water", "matcha_latte"],
    cafePersona: "The Chatter",
    vibeLevel: 82,
    vibeLabel: "Social Butterfly",
    luckyCharm: "AirPods",
    tablemates: ["cappuccino", "chai"],
    neighboringTables: ["hot_black", "americano"],
  },
  hot_black: {
    key: "hot_black",
    title: "You're Hot Black Coffee",
    blurb: "Direct, no-frills, and effective. You value clarity and momentum.",
    explanation: "You're Hot Black Coffee because you cut through the noise. Your responses show you favor directness and efficiency—no time for fluff, just pure momentum.",
    traits: ["decisive", "efficient", "no-nonsense"],
    colorClass: "from-neutral-500 to-neutral-800",
    bestPairings: ["breakfast_sandwich", "croissant"],
    worstPairings: ["chai", "matcha_latte"],
    cafePersona: "Locked In",
    vibeLevel: 95,
    vibeLabel: "Pure Focus",
    luckyCharm: "Noise Cancelling Headphones",
    tablemates: ["espresso", "americano"],
    neighboringTables: ["chai", "iced_milk_coffee"],
  },
  americano: {
    key: "americano",
    title: "You're an Americano",
    blurb: "Reliable and grounded. You keep things simple without being plain.",
    explanation: "You're an Americano because you're dependable without drama. Your quiz answers reflect someone who values substance and consistency over trends.",
    traits: ["steady", "reliable", "grounded"],
    colorClass: "from-slate-400 to-slate-700",
    bestPairings: ["croissant", "breakfast_sandwich"],
    worstPairings: ["avocado_toast", "chai"],
    cafePersona: "Productivity Hacker",
    vibeLevel: 88,
    vibeLabel: "Steady Grind",
    luckyCharm: "Planner",
    tablemates: ["hot_black", "breakfast_sandwich"],
    neighboringTables: ["avocado_toast", "secret_chair"],
  },
  cappuccino: {
    key: "cappuccino",
    title: "You're a Cappuccino",
    blurb: "Warm and social with balanced taste. You like a cozy scene that still moves.",
    explanation: "You're a Cappuccino because you bring warmth to any situation. Your choices show you're social yet balanced—appreciating connection without losing yourself in the noise.",
    traits: ["welcoming", "balanced", "stylish"],
    colorClass: "from-amber-300 to-amber-600",
    bestPairings: ["croissant", "chai"],
    worstPairings: ["espresso", "iced_water"],
    cafePersona: "Aura Farmer",
    vibeLevel: 78,
    vibeLabel: "Cozy Vibes",
    luckyCharm: "Tote Bag",
    tablemates: ["chai", "iced_milk_coffee"],
    neighboringTables: ["espresso", "hot_black"],
  },
  espresso: {
    key: "espresso",
    title: "You're an Espresso Shot",
    blurb: "Bold, focused bursts. You go hard, then ship.",
    explanation: "You're an Espresso Shot because you operate in bursts of pure intensity. Your quiz reveals you tackle challenges head-on with maximum focus, then move to the next thing.",
    traits: ["intense", "decisive", "efficient"],
    colorClass: "from-orange-300 to-orange-700",
    bestPairings: ["breakfast_sandwich", "croissant"],
    worstPairings: ["matcha_latte", "iced_water"],
    cafePersona: "Sprint Master",
    vibeLevel: 98,
    vibeLabel: "Peak Intensity",
    luckyCharm: "Charger Plug",
    tablemates: ["hot_black", "americano"],
    neighboringTables: ["matcha_latte", "iced_water"],
  },
  iced_water: {
    key: "iced_water",
    title: "You're Iced Water",
    blurb: "Cool, clear, and refreshing. You cut through noise and keep it light.",
    explanation: "You're Iced Water because you keep things simple and refreshing. Your answers show you're low-maintenance and clear-headed—no need for extra complications.",
    traits: ["chill", "clean", "minimalist"],
    colorClass: "from-cyan-300 to-cyan-600",
    bestPairings: ["avocado_toast", "breakfast_sandwich"],
    worstPairings: ["cappuccino", "chai"],
    cafePersona: "Zen Observer",
    vibeLevel: 45,
    vibeLabel: "Ultra Chill",
    luckyCharm: "Water Bottle",
    tablemates: ["avocado_toast", "matcha_latte"],
    neighboringTables: ["espresso", "cappuccino"],
  },
  breakfast_sandwich: {
    key: "breakfast_sandwich",
    title: "You're a Breakfast Sandwich",
    blurb: "Practical and dependable. You bring the group together and get things done.",
    explanation: "You're a Breakfast Sandwich because you're the practical anchor people count on. Your choices reflect reliability and substance—you get things done without fanfare.",
    traits: ["grounded", "practical", "dependable"],
    colorClass: "from-yellow-300 to-yellow-600",
    bestPairings: ["iced_milk_coffee", "hot_black"],
    worstPairings: ["croissant", "avocado_toast"],
    cafePersona: "The Anchor",
    vibeLevel: 85,
    vibeLabel: "Steady Power",
    luckyCharm: "Multi-Tool",
    tablemates: ["americano", "hot_black"],
    neighboringTables: ["croissant", "secret_chair"],
  },
  chai: {
    key: "chai",
    title: "You're a Chai Latte",
    blurb: "Cozy, creative, and a touch unconventional. You're warm with a little spark.",
    explanation: "You're a Chai Latte because you blend comfort with creativity. Your personality shows warmth and a unique twist—familiar yet always interesting.",
    traits: ["creative", "cozy", "quirky"],
    colorClass: "from-rose-300 to-rose-600",
    bestPairings: ["croissant", "avocado_toast"],
    worstPairings: ["hot_black", "espresso"],
    cafePersona: "Creative Spirit",
    vibeLevel: 72,
    vibeLabel: "Cozy Creativity",
    luckyCharm: "Vintage Mug",
    tablemates: ["cappuccino", "matcha_latte"],
    neighboringTables: ["hot_black", "espresso"],
  },
  avocado_toast: {
    key: "avocado_toast",
    title: "You're Avocado Toast",
    blurb: "Trendy with substance. You like trying new things and making them your own.",
    explanation: "You're Avocado Toast because you embrace the new while staying authentic. Your quiz shows you're adventurous and health-conscious—trendy, but with real substance.",
    traits: ["trendy", "adventurous", "authentic"],
    colorClass: "from-lime-300 to-lime-600",
    bestPairings: ["matcha_latte", "iced_water"],
    worstPairings: ["breakfast_sandwich", "americano"],
    cafePersona: "Trendsetter",
    vibeLevel: 92,
    vibeLabel: "Main Character Energy",
    luckyCharm: "Reusable Cup",
    tablemates: ["matcha_latte", "chai"],
    neighboringTables: ["americano", "hot_black"],
  },
  croissant: {
    key: "croissant",
    title: "You're a Croissant",
    blurb: "Classic with finesse. You appreciate craft and little luxuries.",
    explanation: "You're a Croissant because you value craft and intentional beauty. Your answers reveal an appreciation for the finer things—elegant, refined, but never overdone.",
    traits: ["elegant", "refined", "intentional"],
    colorClass: "from-fuchsia-300 to-fuchsia-600",
    bestPairings: ["cappuccino", "matcha_latte"],
    worstPairings: ["iced_water", "breakfast_sandwich"],
    cafePersona: "The Aesthete",
    vibeLevel: 68,
    vibeLabel: "Refined Taste",
    luckyCharm: "Fountain Pen",
    tablemates: ["cappuccino", "chai"],
    neighboringTables: ["breakfast_sandwich", "iced_water"],
  },
  secret_chair: {
    key: "secret_chair",
    title: "You're… The Secret Chair",
    blurb: "Pure chaos energy. You bend the rules and somehow it works.",
    explanation: "You're The Secret Chair because you exist outside normal categories. Your quiz choices were delightfully unpredictable—you're chaotic, rare, and somehow it all works.",
    traits: ["chaotic", "rare", "unpredictable"],
    colorClass: "from-indigo-300 to-indigo-700",
    bestPairings: ["secret_chair", "chai"],
    worstPairings: ["americano", "hot_black"],
    cafePersona: "Chaos Agent",
    vibeLevel: 100,
    vibeLabel: "Pure Chaos",
    luckyCharm: "Random Object",
    tablemates: ["chai", "secret_chair"],
    neighboringTables: ["americano", "breakfast_sandwich"],
  },
};
